"""Pydantic data models and enumerations for LLM gateway and advisories."""

from enum import StrEnum

from pydantic import BaseModel, Field

from malabar_watch.risk_engine.models import RiskLevel


class LLMProviderType(StrEnum):
    """Supported LLM providers and fallback tiers."""

    GEMINI = "gemini"
    GROQ = "groq"
    TEMPLATE = "template"


class BilingualAdvisory(BaseModel):
    """Structured bilingual early-warning advisory generated by the LLM layer."""

    district_id: str = Field(description="District or micro-zone identifier")
    risk_level: RiskLevel = Field(description="Deterministic risk severity tier")
    summary_en: str = Field(
        description="2-sentence clear overview of current rainfall and risk in English"
    )
    summary_ml: str = Field(
        description="2-sentence clear overview of current rainfall and risk in Malayalam"
    )
    advisory_en: str = Field(
        description="Actionable safety guidance for residents in English"
    )
    advisory_ml: str = Field(
        description="Actionable safety guidance for residents in Malayalam"
    )
    provider_used: str = Field(
        description="Provider fulfilling the request: 'gemini', 'groq', or 'template'"
    )
    latency_ms: int = Field(
        default=0, description="Round-trip response latency in milliseconds"
    )
